Repository HH99-NearBy/HH99-NearBy-BE, pull requests merged in 2022-10, with the labels that each got.

#212 feat(찜기능): 찜 등록한 챌린지 목록
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/WishList.java
  src/main/java/com/hh99/nearby/repository/WishListRepository.java
  src/main/java/com/hh99/nearby/wishlist/controller/WishListController.java
  src/main/java/com/hh99/nearby/wishlist/dto/MypageWishList.java
  src/main/java/com/hh99/nearby/wishlist/dto/MypageWishResponseDto.java
  src/main/java/com/hh99/nearby/wishlist/dto/WishListRequestDto.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: feature

#213 feat(찜기능): 찜 등록한 챌린지 목록
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/WishList.java
  src/main/java/com/hh99/nearby/repository/WishListRepository.java
  src/main/java/com/hh99/nearby/wishlist/controller/WishListController.java
  src/main/java/com/hh99/nearby/wishlist/dto/MypageWishList.java
  src/main/java/com/hh99/nearby/wishlist/dto/MypageWishResponseDto.java
  src/main/java/com/hh99/nearby/wishlist/dto/WishListRequestDto.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: feature

#216 feat(모니터링): 커스텀 익셉션 적용 및 센트리 모니터링 적용 #214 #215
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/exception/ErrorCode.java
  src/main/java/com/hh99/nearby/exception/PrivateException.java
  src/main/java/com/hh99/nearby/exception/PrivateResponseBody.java
  src/main/java/com/hh99/nearby/exception/RestApiExceptionHandler.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/util/GetClientIp.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: feature

#217 feat(모니터링): 커스텀 익셉션 적용 및 센트리 모니터링 적용
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/exception/ErrorCode.java
  src/main/java/com/hh99/nearby/exception/PrivateException.java
  src/main/java/com/hh99/nearby/exception/PrivateResponseBody.java
  src/main/java/com/hh99/nearby/exception/RestApiExceptionHandler.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/util/GetClientIp.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: feature

#220 fix(모니터링): 센트리 모니터링 에러메시지 수정
  src/main/java/com/hh99/nearby/exception/PrivateException.java
Labels: fix

#221 fix(모니터링): 센트리 모니터링 에러메시지 수정
  src/main/java/com/hh99/nearby/exception/PrivateException.java
Labels: fix

#222 fix(로그인): 로그인 요청시 레벨업 남은시간 정보 추가
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix

#223 fix(로그인): 로그인 요청시 레벨업 남은시간 정보 추가
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix, feature

#224 fix(로그인): 로그인 요청시 레벨업 남은시간 정보 추가
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#235 fix(코드 리팩토링): 카카오 로그인시 남은시간 정보 추가 및 코드 리팩토링
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberPageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#236 fix(코드 리팩토링): 카카오 로그인시 남은시간 정보 추가 및 코드 리팩토링
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberPageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#237 fix(카카오 로그인): 카카오 로그인시 전송되는 정보 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#238 fix(카카오 로그인): 카카오 로그인시 전송되는 정보 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#241 fix(리이슈): 리이슈 응답 메시지 수정
  src/main/java/com/hh99/nearby/security/jwt/AuthenticationEntryPointException.java
Labels: fix

#242 fix(마이페이지): finishchallenge startDay 추가
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#243 fix(마이페이지): finishchallenge startDay 추가
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#246 feat(README): README 이미지작업
  Images/image (2).png
Labels: fix, feature

#247 feat(README): README 이미지작업
  Images/image (2).png
Labels: fix, feature

#256 fix(스웨거): 스웨거 제목 변경
  Images/Architecture.png
  Images/GitFlow.png
  Images/commit message.PNG
  README.md
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
Labels: fix

#257 fix(스웨거): 스웨거 제목 변경
  Images/Architecture.png
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
Labels: fix

#258 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  Images/WireFrame.PNG
  README.md
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/controller/SessionController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/dto/request/ChatMessageDto.java
  src/main/java/com/hh99/nearby/chat/dto/request/SessionRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/response/SessionMemberDto.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/chat/service/Scheduler.java
  src/main/java/com/hh99/nearby/chat/service/ViewChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/Chat.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/entity/RankPage.java
  src/main/java/com/hh99/nearby/entity/RefreshToken.java
  src/main/java/com/hh99/nearby/exception/PrivateException.java
  src/main/java/com/hh99/nearby/exception/RestApiExceptionHandler.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RankPageRepository.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
  src/main/java/com/hh99/nearby/security/dto/TokenDto.java
  src/main/java/com/hh99/nearby/security/jwt/JwtSecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/dto/response/KakaoSignUpResponseDto.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: fix

#259 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/controller/SessionController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/dto/request/ChatMessageDto.java
  src/main/java/com/hh99/nearby/chat/dto/request/SessionRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/response/SessionMemberDto.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/chat/service/Scheduler.java
  src/main/java/com/hh99/nearby/chat/service/ViewChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/Chat.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/entity/RankPage.java
  src/main/java/com/hh99/nearby/entity/RefreshToken.java
  src/main/java/com/hh99/nearby/exception/PrivateException.java
  src/main/java/com/hh99/nearby/exception/RestApiExceptionHandler.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RankPageRepository.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
  src/main/java/com/hh99/nearby/security/dto/TokenDto.java
  src/main/java/com/hh99/nearby/security/jwt/JwtSecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/dto/response/KakaoSignUpResponseDto.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
  src/main/java/com/hh99/nearby/wishlist/service/WishListService.java
Labels: fix

#260 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
Labels: fix

#261 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
Labels: fix

#263 fix(랭킹페이지): 카카오 로그인 시 초기 그래프 생성
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#264 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
Labels: fix

#265 fix(코드 리팩토링): 사용되지 않는 코드 제거 및 코드 리팩토링
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
Labels: fix

#266 fix(코드 리펙토링): return 부분 수정
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix

#267 fix(코드 리펙토링): return 부분 수정
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix
