Repository HH99-NearBy/HH99-NearBy-BE, pull requests merged in 2022-09, with the labels that each got.

#15 feat(카카오 로그인 ): 카카오 로그인 구현중
  build.gradle
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/KakaoRequestDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/resources/application.properties
Labels: feature

#16 feat(카카오 로그인 ): 카카오 로그인 구현중
  build.gradle
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/KakaoRequestDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/resources/application.properties
Labels: feature

#19 fix(로그인 ): 로그인 컨트롤러 코드수정
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
Labels: fix

#20 fix(로그인 ): 로그인 컨트롤러 코드수정
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
Labels: fix

#21 feat(회원가입): 회원가입 1차 머지
  .gitignore
  build.gradle
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/dto/SignUpRequestDto.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
Labels: feature

#22 feat(회원가입): 회원가입 1차 머지
  .gitignore
  build.gradle
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/dto/SignUpRequestDto.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
Labels: feature

#23 fix(프로퍼티): 프로퍼티 수정
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/LoginRequestDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/security/UserDetailsImpl.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/resources/application.properties
Labels: fix

#25 fix(스프링 시큐리티): 스프링 시큐리티 오류수정
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
Labels: fix

#29 fix(카카오로그인,회원가입): 카카오로그인 수정 및 회원가입
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#30 fix(카카오로그인,회원가입): 카카오로그인 수정 및 회원가입
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#31 feat(회원가입): 이메일 중복 검사 추가
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#32 feat(회원가입): 이메일 중복 검사 추가
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#35 feat(챌린지): 챌린지 글작성 구현
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/signup/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/signup/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/repository/RefreshTokenRepository.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#36 feat(챌린지): 챌린지 글작성 구현
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/signup/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/signup/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/repository/RefreshTokenRepository.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#37 feat(챌린지 ): 챌린지 태그, 수정, 삭제 구현
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/KakaoRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/request/LoginRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
Labels: feature

#38 feat(챌린지 ): 챌린지 태그, 수정, 삭제 구현
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/KakaoRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/request/LoginRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
Labels: feature

#39 feat(상세 모달): 상세모달 페이지 1차 완성
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/detail/controller/DetailController.java
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RefreshTokenRepository.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#40 feat(상세 모달): 상세모달 페이지 1차 완성
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/detail/controller/DetailController.java
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RefreshTokenRepository.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#42 feat(마이페이지): 마이페이지(50%) 및 프로필수정 기능 구현
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberResponseDto.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageChallengeList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
Labels: feature

#43 feat(마이페이지): 마이페이지(50%) 및 프로필수정 기능 구현
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberResponseDto.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageChallengeList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
Labels: feature

#45 feat(메인페이지): 메인페이지 기능 구현(80%)완료
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageChallengeList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#46 feat(메인페이지): 메인페이지 기능 구현(80%)완료
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageChallengeList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: feature

#49 fix(회원가입): 이메일 중복체크 수정
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#50 fix(회원가입): 이메일 중복체크 수정
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#52 feat(메인페이지): MainPageResponseDto 생성
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
Labels: feature

#53 feat(메인페이지): MainPageResponseDto 생성
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
Labels: feature

#55 feat(메인페이지): 무한스크롤 구현완료
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: feature

#56 feat(메인페이지): 무한스크롤 구현완료
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: feature

#58 feat(스웨거): 스웨거 추가
  build.gradle
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
Labels: feature

#59 feat(스웨거): 스웨거 추가
  build.gradle
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/swagger/SwaggerConfig.java
Labels: feature

#60 feat(웹소켓): 웹소켓 개발중
  build.gradle
  src/main/java/com/hh99/nearby/chat/WebsocketConfig.java
  src/main/java/com/hh99/nearby/chat/controller/ChatMessageController.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/hh99/nearby/chat/entity/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoomMember.java
  src/main/java/com/hh99/nearby/chat/repository/ChatMessageRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatMessageService.java
  src/main/java/com/hh99/nearby/chat/service/ChatRoomService.java
Labels: feature

#61 feat(웹소켓): 웹소켓 개발중
  build.gradle
  src/main/java/com/hh99/nearby/chat/WebsocketConfig.java
  src/main/java/com/hh99/nearby/chat/controller/ChatMessageController.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/hh99/nearby/chat/entity/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoomMember.java
  src/main/java/com/hh99/nearby/chat/repository/ChatMessageRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatMessageService.java
  src/main/java/com/hh99/nearby/chat/service/ChatRoomService.java
Labels: feature

#62 feat(웹소켓): 웹소켓 구현완료
  build.gradle
  src/main/java/com/hh99/nearby/chat/WebsocketConfig.java
  src/main/java/com/hh99/nearby/chat/controller/ChatMessageController.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/hh99/nearby/chat/entity/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoomMember.java
  src/main/java/com/hh99/nearby/chat/repository/ChatMessageRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatMessageService.java
  src/main/java/com/hh99/nearby/chat/service/ChatRoomService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/Kakaocode.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: feature

#63 feat(웹소켓): 웹소켓 구현완료
  build.gradle
  src/main/java/com/hh99/nearby/chat/WebsocketConfig.java
  src/main/java/com/hh99/nearby/chat/controller/ChatMessageController.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageRequestDto.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/hh99/nearby/chat/entity/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/ChatRoomMember.java
  src/main/java/com/hh99/nearby/chat/repository/ChatMessageRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRoomRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatMessageService.java
  src/main/java/com/hh99/nearby/chat/service/ChatRoomService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/Kakaocode.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: feature

#64 feat(웹소켓): 웹소켓 구현완료
  src/main/java/com/hh99/nearby/chat/Dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/Dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/entity/Chat.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
Labels: feature

#65 feat(웹소켓): 웹소켓 구현완료
  src/main/java/com/hh99/nearby/chat/Dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/Dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/entity/Chat.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
Labels: feature

#67 feat(git action): 깃 액션 기본 테스트
  .github/workflows/main.yml
Labels: feature

#68 feat(git action): 깃 액션 기본 테스트
  .github/workflows/main.yml
Labels: feature

#71 feat(git action): 깃 액션 기본 테스트
  .github/workflows/main.yml
Labels: feature

#73 feat(메인페이지): 메인페이지 참여인원 추가
  .github/workflows/main.yml
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
Labels: feature

#74 feat(메인페이지): 메인페이지 참여인원 추가
  .github/workflows/main.yml
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
Labels: feature

#77 feat(화상채팅): 화상채팅적용 및 JWT응답수정
  build.gradle
  src/main/java/com/hh99/nearby/LoginController.java
  src/main/java/com/hh99/nearby/ResponseDto.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/controller/SessionController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/dto/SessionRequestDto.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/login/controller/OrginLoginController.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/security/CorsConfiguration.java
  src/main/java/com/hh99/nearby/security/UserDetailsImpl.java
  src/main/java/com/hh99/nearby/security/UserDetailsServiceImpl.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/resources/openvidu-selfsigned.jks
Labels: fix, feature

#78 fix(웹소켓): 실시간채팅 Level 로직 변경
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/Chat.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#79 fix(웹소켓): 실시간채팅 Level 로직 변경
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/dto/ChatRoom.java
  src/main/java/com/hh99/nearby/chat/entity/Chat.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#80 fix(웹소켓): 실시간채팅 Level 로직 변경
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/CorsConfiguration.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#81 fix(웹소켓): 실시간채팅 Level 로직 변경
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/CorsConfiguration.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#82 feat(실시간채팅): 실시간채팅입장시 기존인원 조회 #47
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/dto/SessionMemberDto.java
  src/main/java/com/hh99/nearby/chat/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
Labels: fix, feature

#86 fix(마이페이지): 레벨기능 추가, 내가 완료한 페이지 구현
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
Labels: fix

#87 fix(마이페이지): 레벨기능 추가, 내가 완료한 페이지 구현
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishList.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
Labels: fix

#88 fix(회원가입): 이메일 인증 변경
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
Labels: fix

#91 feat(랭킹페이지): 랭킹페이지 1차 구현 완료
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/controller/RankController.java
  src/main/java/com/hh99/nearby/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RankPageRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
Labels: feature

#92 feat(랭킹페이지): 랭킹페이지 1차 구현 완료
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/MemberChallenge.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/controller/RankController.java
  src/main/java/com/hh99/nearby/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/repository/RankPageRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
Labels: feature

#94 feat(마이페이지): 마이페이지 랭킹,그래프 추가
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: feature

#96 feat(스케줄러): 스케줄러 기능구현
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
Labels: feature

#97 feat(스케줄러): 스케줄러 기능구현
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
Labels: feature

#98 fix(JWT 토큰) :리이슈 완성 및 토큰만료 시간 변경
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/entity/RefreshToken.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/controller/TokenController.java
  src/main/java/com/hh99/nearby/security/dto/ReissueDto.java
  src/main/java/com/hh99/nearby/security/jwt/AuthenticationEntryPointException.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/service/TokenService.java
Labels: fix, feature

#99 fix(JWT 토큰) :리이슈 완성 및 토큰만료 시간 변경
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/entity/RefreshToken.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/controller/TokenController.java
  src/main/java/com/hh99/nearby/security/dto/ReissueDto.java
  src/main/java/com/hh99/nearby/security/jwt/AuthenticationEntryPointException.java
  src/main/java/com/hh99/nearby/security/jwt/JwtFilter.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/java/com/hh99/nearby/security/service/TokenService.java
Labels: fix, feature

#100 feat(마이페이지): 마이페이지에서 랭킹 바로 조회
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: feature

#101 feat(마이페이지): 마이페이지에서 랭킹 바로 조회
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: feature

#102 fix(랭킹페이지): myRank int -> Long
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: fix

#106 Fix/rank
  src/main/java/com/hh99/nearby/rank/dto/MyRankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: fix

#107 Fix/rank
  src/main/java/com/hh99/nearby/rank/dto/MyRankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: fix

#109 fix(상세 모달): 챌린지 참여하기,취소하기 수정 #33
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
Labels: fix

#110 fix(상세 모달): 챌린지 참여하기,취소하기 수정
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
Labels: fix

#111 fix(상세모달): 참여하기 제한인원 만큼 신청가능하게 로직변경
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
Labels: fix

#112 fix(상세모달): 참여하기 제한인원 만큼 신청가능하게 로직변경
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
Labels: fix

#119 fix(전체): 전체적인 코드 수정
  .gitignore
  src/main/java/com/hh99/nearby/LoginController.java
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/controller/SessionController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#120 fix(전체): 전체적인 코드 수정
  .gitignore
  src/main/java/com/hh99/nearby/LoginController.java
  src/main/java/com/hh99/nearby/NearbyApplication.java
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/ChatRoomController.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/controller/SessionController.java
  src/main/java/com/hh99/nearby/chat/dto/ChatMessage.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/security/jwt/TokenProvider.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: fix

#127 fix(메인페이지): 메인페이지 - 무한스크롤 조건 변경으로 인한 QueryDsl 적용 #125
  .gitignore
  build.gradle
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/config/QueryDslConfig.java
  src/main/java/com/hh99/nearby/security/controller/TokenController.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
Labels: fix, feature

#128 fix(메인페이지): 메인페이지 - 무한스크롤 조건 변경으로 인한 QueryDsl 적용
  .gitignore
  build.gradle
  src/main/java/com/hh99/nearby/chat/Scheduler.java
  src/main/java/com/hh99/nearby/chat/config/ChatConfig.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/service/ChatService.java
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/config/QueryDslConfig.java
  src/main/java/com/hh99/nearby/security/controller/TokenController.java
  src/main/java/com/hh99/nearby/security/jwt/service/TokenService.java
Labels: fix, feature

#129 feat(검색기능): 검색기능 구현완료
  .gitignore
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/search/controller/SearchController.java
  src/main/java/com/hh99/nearby/search/dto/SearchResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: feature

#131 fix(랭킹페이지): 랭킹페이지 수정 완료
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/RankPage.java
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/Rank.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix, feature

#132 fix(랭킹페이지): 랭킹페이지 수정 완료
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/RankPage.java
  src/main/java/com/hh99/nearby/login/dto/response/LoginResponseDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/rank/service/Rank.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix, feature

#133 fix(랭킹페이지): score,rank 수정
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#134 fix(랭킹페이지): score,rank 수정
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/util/LevelCheck.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#135 fix(랭킹페이지): 랭킹정렬 수정
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: fix

#140 feat(연관검색어): 연관검색어 기능구현
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/repository/ChallengeRepository.java
  src/main/java/com/hh99/nearby/search/controller/SearchController.java
  src/main/java/com/hh99/nearby/search/dto/RelationWordResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: feature

#142 fix(챌린지페이지): 챌린징 페이지 입장시 기존인원 입장시간 추가
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/SessionMemberDto.java
Labels: fix

#143 fix(챌린지페이지): 챌린징 페이지 입장시 기존인원 입장시간 추가
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/chat/dto/SessionMemberDto.java
Labels: fix

#144 feat(필터링): 메인페이지 필터 구현
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: feature

#145 feat(필터링): 메인페이지 필터 구현
  src/main/java/com/hh99/nearby/mainpage/controller/MainPageController.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: feature

#146 fix(메인페이지): 첼린지 ID 추가
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/entity/Chat.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/search/dto/RelationWordResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix

#147 fix(메인페이지): 첼린지 ID 추가
  src/main/java/com/hh99/nearby/chat/config/StompHandler.java
  src/main/java/com/hh99/nearby/chat/controller/MessageController.java
  src/main/java/com/hh99/nearby/entity/Chat.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/repository/ChatRepository.java
  src/main/java/com/hh99/nearby/search/dto/RelationWordResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix

#149 feat(소셜로그인): 소셜로그인후 닉네임 설정하기
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/NicknameRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
Labels: feature

#150 feat(소셜로그인): 소셜로그인후 닉네임 설정하기
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/NicknameRequestDto.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
Labels: feature

#152 모니터링을 위한 센트리 적용
  build.gradle
  src/main/java/com/hh99/nearby/login/service/LoginService.java
Labels: feature

#153 fix/email,rank
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#154 fix/email,rank
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/LoginService.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#155 fix(이메일 인증): 이메일 인증 리다이렉트 url 변경
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
Labels: fix

#157 카카오 로그인 오타수정 및 깃액션 테스트
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
Labels: fix

#158 카카오 로그인 오타수정 및 깃액션 테스트
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
Labels: fix

#159 fix(이메일 인증): 이메일 리다이렉트 url git secret 추가
  .github/workflows/main.yml
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/resources/application.yaml
Labels: fix

#160 fix(이메일 인증): 이메일 리다이렉트 url git secret 추가
  .github/workflows/main.yml
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/resources/application.yaml
Labels: fix

#161 fix(스프링 시큐리티): 스프링 시큐리티 설정 추가
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: fix

#162 fix(스프링 시큐리티): 스프링 시큐리티 설정 추가
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
Labels: fix

#165 fix(회원가입): 회원가입 url 변수변경
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
Labels: error, fix

#166 fix(회원가입): 회원가입 url 변수변경
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
Labels: error, fix

#167 fix(회원가입): 회원가입시 닉네임체크 로직 변경
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#168 fix(회원가입): 회원가입시 닉네임체크 로직 변경
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#169 fix(랭킹페이지): 0등일때 등수 표시 --- 으로 변경
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
Labels: fix

#170 fix(랭킹페이지): 0등일때 등수 표시 --- 으로 변경
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
Labels: fix

#173 feat(마이페이지): 마이페이지 api 수정
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/login/service/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/login/service/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/login/service/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MemberPageResponseDto.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageJoinList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/contorller/service/EmailService.java
  src/main/java/com/hh99/nearby/signup/contorller/service/SignUpService.java
  src/main/resources/static/index.html
Labels: fix

#174 fix(마이페이지): 0등일때 등수 표시 --- 으로 변경
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#175 fix(마이페이지): 0등일때 등수 표시 --- 으로 변경
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#176 fix(마이페이지): 마이페이지 api 추가수정
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishResponseDto.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageJoinResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#177 fix(마이페이지): 마이페이지 api 추가수정
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageFinishResponseDto.java
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageJoinResponseDto.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#178 fix(마이페이지): JoinList 참여인원 추가
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageJoinList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#179 fix(마이페이지): JoinList 참여인원 추가
  src/main/java/com/hh99/nearby/mypage/dto/response/MypageJoinList.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
Labels: fix

#180 fix(카카오로그인): 카카오로그인 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#181 fix(카카오로그인): 카카오로그인 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#182 gitaction 사용
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#183 gitaction 사용
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#184 fix(깃액션): 깃액션 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#185 fix(깃액션): 깃액션 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
Labels: fix

#187 fix(랭킹페이지): 그래프,스케줄러 수정
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#188 fix(랭킹페이지): 그래프,스케줄러 수정
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/mainpage/dto/MainPageResponseDto.java
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
  src/main/java/com/hh99/nearby/util/Graph.java
  src/main/java/com/hh99/nearby/util/Rank.java
  src/main/java/com/hh99/nearby/util/Score.java
Labels: fix

#189 fix(검색기능): 검색 챌린지 조회시 닉네임 추가
  src/main/java/com/hh99/nearby/search/dto/SearchResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix

#190 fix(검색기능): 검색 챌린지 조회시 닉네임 추가 #126
  src/main/java/com/hh99/nearby/search/dto/SearchResponseDto.java
  src/main/java/com/hh99/nearby/search/service/SearchService.java
Labels: fix

#191 fix(상세모달): 상세모달 요청시 로그인한 유저의 챌린지 참여여부
  src/main/java/com/hh99/nearby/detail/controller/DetailController.java
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/rank/controller/RankController.java
  src/main/java/com/hh99/nearby/entity/rank/dto/MyRankPageDto.java
  src/main/java/com/hh99/nearby/entity/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/entity/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
Labels: fix

#192 fix(상세모달): 상세모달 요청시 로그인한 유저의 챌린지 참여여부
  src/main/java/com/hh99/nearby/detail/controller/DetailController.java
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
  src/main/java/com/hh99/nearby/entity/rank/controller/RankController.java
  src/main/java/com/hh99/nearby/entity/rank/dto/MyRankPageDto.java
  src/main/java/com/hh99/nearby/entity/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/entity/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/signup/service/EmailService.java
Labels: fix

#193 fix(상세모달): 상세모달 isJoin
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
Labels: fix

#194 fix(상세모달): 상세모달 isJoin
  src/main/java/com/hh99/nearby/detail/dto/DetailResponseDto.java
  src/main/java/com/hh99/nearby/detail/service/DetailService.java
Labels: fix

#195 fix(랭킹페이지): 랭킹페이지 정렬 조건 변경
  src/main/java/com/hh99/nearby/rank/controller/RankController.java
  src/main/java/com/hh99/nearby/rank/dto/MyRankPageDto.java
  src/main/java/com/hh99/nearby/rank/dto/RankPageDto.java
  src/main/java/com/hh99/nearby/rank/service/RankPageService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
Labels: fix

#197 fix(랭킹페이지): 그래프 최신 값 오늘부터
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
Labels: fix

#199 fix(카카오로그인): 카카오 로그인/회원가입 구현완료
  src/main/java/com/hh99/nearby/challenge/controller/ChallengeController.java
  src/main/java/com/hh99/nearby/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/hh99/nearby/challenge/service/ChallengeService.java
  src/main/java/com/hh99/nearby/entity/Challenge.java
  src/main/java/com/hh99/nearby/entity/Member.java
  src/main/java/com/hh99/nearby/entity/RefreshToken.java
  src/main/java/com/hh99/nearby/login/controller/LoginController.java
  src/main/java/com/hh99/nearby/login/dto/request/KakaocodeDto.java
  src/main/java/com/hh99/nearby/login/dto/response/KakaoResponseDto.java
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/repository/MemberRepository.java
  src/main/java/com/hh99/nearby/security/SecurityConfiguration.java
  src/main/java/com/hh99/nearby/signup/contorller/SignUpController.java
  src/main/java/com/hh99/nearby/signup/dto/request/KakaodSignUpRequestDto.java
  src/main/java/com/hh99/nearby/signup/dto/request/SignUpRequestDto.java
  src/main/java/com/hh99/nearby/signup/dto/response/KakaoSignUpResponseDto.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#201 gitaction 실행
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
Labels: fix

#202 gitaction 실행
  src/main/java/com/hh99/nearby/mainpage/service/MainPageService.java
Labels: fix

#203 gitaction 실행
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#204 gitaction 실행
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#205 fix(카카오로그인): 카카오로그인 기능 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#206 fix(카카오로그인): 카카오로그인 기능 수정
  src/main/java/com/hh99/nearby/login/service/KakaoLoginService.java
  src/main/java/com/hh99/nearby/signup/service/SignUpService.java
Labels: fix

#208 fix(프로필수정): 프로필수정 jwt 토큰 재발급
  src/main/java/com/hh99/nearby/mypage/controller/MypageController.java
  src/main/java/com/hh99/nearby/mypage/service/MypageService.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix

#209 fix(랭킹페이지): 랭킹페이지 수정
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix

#210 fix(랭킹페이지): 랭킹페이지 수정
  src/main/java/com/hh99/nearby/repository/MemberChallengeRepository.java
  src/main/java/com/hh99/nearby/util/Graph.java
Labels: fix
